In [2]:
import numpy as np

In [2]:
np.__version__

'1.26.0'

In [3]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array2=np.array([[1,2],
                [3,4]])
array2

array([[1, 2],
       [3, 4]])

In [6]:
array3d=np.array([[
    [1,2],
    [3,4]
],[
    [5,6],
    [7,8]
  ]   
])
array3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
array3d.shape

(2, 2, 2)

In [8]:
array3ex=np.array([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[10,11,12],
                   [13,14,15],
                  [16,17,18]]
                  ])
array3ex

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
array3ex.shape

(2, 3, 3)

In [8]:
array4d=np.array([
    [
        [
            [1,2],
            [3,4],
            [5,6]
        ],
        [
            [7,8],
            [9,10],
            [11,12]
        ],
        [
            [13,14],
            [15,16],
            [17,18]
        ]
    ],
    [
        [
            [19,20],
            [21,22],
            [23,24]
        ],
        [
            [25,26],
            [27,28],
            [29,30]
        ],
        [
            [31,32],
            [33,34],
            [35,36]
        ]
    ]
])
array4d

array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18]]],


       [[[19, 20],
         [21, 22],
         [23, 24]],

        [[25, 26],
         [27, 28],
         [29, 30]],

        [[31, 32],
         [33, 34],
         [35, 36]]]])

In [13]:
array4d.shape

(2, 3, 3, 2)

In [5]:
import numpy as np
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
C = np.dot(A, B)
print("Matrix a:\n",A)
print("Matrix a:\n",B)
print("Matrix Multiplication (A X B):\n", C)

Matrix a:
 [[1 2]
 [3 4]]
Matrix a:
 [[5 6]
 [7 8]]
Matrix Multiplication (A X B):
 [[19 22]
 [43 50]]


In [9]:
array4d.ndim

4

In [11]:
print(A.ndim)

2


In [13]:
array6=np.array([1,2,3,4,5,], ndmin=2)
array6

array([[1, 2, 3, 4, 5]])

In [14]:
print(array6.ndim)

2


In [3]:
arrex=np.array([1,2,3,4,5])
arrex.shape

(5,)

In [6]:
print(A[0][1])

2


In [7]:
array7=np.array([[1,2],[3.3,4]])
array7

array([[1. , 2. ],
       [3.3, 4. ]])

In [8]:
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [12]:
ch_arr2=np.array(["Supervised", "unSupervised",
                  "sEMi-supervised","reinforcment"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcment'],
      dtype='<U15')